### ISSUE TITLE
Need to be able to get public key ID from a zcap used to invoke VC issue signature

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-vc-issuer#10]
When using a zcap to sign a VC with an `assertionMethod` key, we need to know the public key ID to use -- which isn't the same as the `invocationTarget` in the zcap. We need to figure out how to model that and implement it.

**Comment by mattcollier** [comment]
This has landed, `verificationMethod` is now included in the `issuer` object.
