### ISSUE TITLE
Add `cryptosuites` to issuer config

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-vc-issuer#128]
`cryptosuites` should be an array of cryptosuite options objects that will be used by the issuer. It should look like this:

`cryptosuites: [{cryptosuite: 'cryptosuite name (same values as the old suiteName), options: {mandatoryPointers}}, {...}]`

Support for `suiteName` should remain for backwards compatibility, but only one of `cryptosuites` or `suiteName` should be used.

**Comment by dlongley** [comment]
See #131 as well.

**Comment by aljones15** [comment]
Work on this was started here: https://github.com/digitalbazaar/bedrock-vc-issuer/tree/add-issuer-provision-option-cryptosuites

**Comment by dlongley** [comment]
I don't know why I wrote that we'd want this field to be an array, there's just one cryptosuite per issuer instance, so we can simplify that bit.

**Comment by dlongley** [comment]
This work is in progress now -- existing work is out of date and we need a slightly different direction. Also, the reason I wrote that we wanted an array was to support proof sets, so we do want it to function that way.
