### ISSUE TITLE
HTTP Validation

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-issuer#14]
Work has begun here: https://github.com/digitalbazaar/bedrock-vc-issuer/tree/http-validation

Here is a sample presentation: https://gist.github.com/mattcollier/349fe541d793e0d61280254f554e2922#file-vp-json-L4

**Comment by mattcollier** [comment]
@aljones15 The test that have been written so far are all passing at this moment, if you see anything other than that, please let me know.

**Comment by mattcollier** [comment]
The presentation schema was automagically created using this tool: https://jsonschema.net/

I figured that would make a good starting point.  The idea was to break out `capability` into a separate schema etc.  Also, probably want to remove the automatically generated wildcard `pattern` thing unless it's useful.

**Comment by aljones15** [comment]
- [ ] use [jsonschema.net to auto generate schemas](https://jsonschema.net/)
- [ ] break capability out into it's own validator

**Comment by mattcollier** [comment]
@aljones15 there is now this branch which will hopefully be released soon: https://github.com/digitalbazaar/bedrock-credentials-context/tree/new-url

If you use this in the same way as `bedrock-security-context` you will be able to pull the URLcontext URL constant instead of using the string literal.

https://gist.github.com/mattcollier/349fe541d793e0d61280254f554e2922#file-vp-json-L4

I'll keep you posted on when `bedrock-credentials-context` is released.

**Comment by mattcollier** [comment]
bdrock-credentials-context@1 released: https://github.com/digitalbazaar/bedrock-credentials-context

**Comment by aljones15** [comment]
- [ ] use bedrock-credentials-context and the resulting constants to specify the jsonLd.context for the schemas.

**Comment by aljones15** [comment]
@mattcollier should we consider this closed now?

**Comment by mattcollier** [comment]
Created a new issue for further work: https://github.com/digitalbazaar/bedrock-vc-issuer/issues/23
