### ISSUE TITLE
walletClient.getControllerKey

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-issuer#16]
https://github.com/digitalbazaar/bedrock-vc-issuer/blob/021ed419657f8e865f149b896932d3ab16f43f66/lib/issuer.js#L27-L28

`walletClient` does not implement the `getControllerKey` method.  Where is that method supposed to come from?

**Comment by aljones15** [comment]
from the kms system usually: https://github.com/digitalbazaar/bedrock-web-kms

**Comment by dlongley** [comment]
@mattcollier, it is replaced by this: https://github.com/digitalbazaar/bedrock-vc-issuer/blob/021ed419657f8e865f149b896932d3ab16f43f66/lib/instances.js#L141

**Comment by mattcollier** [comment]
OK, great, ty.

**Comment by mattcollier** [comment]
Resolved.
