### ISSUE TITLE
walletClient.storage.get

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-issuer#17]
https://github.com/digitalbazaar/bedrock-vc-issuer/blob/021ed419657f8e865f149b896932d3ab16f43f66/lib/configurations.js#L20-L21

`walletClient` does not implement a `storage` API, where does this come from?

**Comment by dlongley** [comment]
It is replaced by this: https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js

**Comment by dlongley** [comment]
This API is no longer used, closing.
