### ISSUE TITLE
Prune package.json for unused deps

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-vc-issuer#38]

**Comment by aljones15** [comment]
- [x] means used in the project

Deps:
- [ ] assert-plus
- [ ]  auth-header
- [ ] axios
- [ ] bs58
- [ ] cors
- [ ] crypto-ld
- [ ] did-io
- [ ] did-method-key
- [ ] did-veres-one
- [ ] edv-client
- [ ] jsonld-signatures
- [ ] lru-cache
- [ ] opcald
- [ ] vc-js
- [ ] vc-revocation-list
- [ ] webkms-client

peerDeps:
- [ ] bedrock
- [ ] bedrock-account
- [ ] bedrock-credentials-context
- [ ] bedrock-did-context
- [ ] bedrock-express
- [ ] bedrock-https-agent
- [ ] bedrock-jsonld-document-loader
- [ ] bedrock-passport
- [ ] bedrock-permission
- [ ] bedrock-profile
- [ ] bedrock-permission
- [ ] bedrock-passport
- [ ] bedrock-mongodb
- [ ] bedrock-security-context
- [ ] bedrock-server
- [ ] bedrock-validation
- [ ] bedrock-vc-revocation-list-context
- [ ] bedrock-veres-one-context
- [ ] bedrock-zcap-storage

**Comment by aljones15** [comment]
`bedrock-permission` is required by `bedrock-account`

**Comment by dlongley** [comment]
This was done, closing.
