### ISSUE TITLE
Validate the presentation in the DID authentication endpoint

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-issuer#54]
https://github.com/digitalbazaar/bedrock-vc-issuer/blob/credentials-route-plus-instance/lib/http.js#L40

This process should involve sending the presentation off to a HTTP verifier API to have the presentation validated.

The presentation should contain a challenge (nonce) that was given to the presenter to defend against replay attacks.

A details specification will need to be provided before proceeding with this item.

**Comment by dlongley** [comment]
Additional work on the HTTP verifier API may be a blocker for implementing this here. See: https://github.com/digitalbazaar/bedrock-vc-verifier/issues/10

**Comment by dlongley** [comment]
This kind of authentication is no longer part of this module, closing.
