### ISSUE TITLE
Add tests for RLC endpoints

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-vc-issuer#55]
RLC is the Revocation List tests.

You will need to test this endpoint:

https://github.com/digitalbazaar/bedrock-vc-issuer/blob/ade562c8cf5bcbeda2a1caca8cbfbe1538109aca/lib/http.js#L124-L186

Which calls on:

https://github.com/digitalbazaar/bedrock-vc-issuer/blob/ade562c8cf5bcbeda2a1caca8cbfbe1538109aca/lib/issuer.js#L106-L132

And this endpoint:

https://github.com/digitalbazaar/bedrock-vc-issuer/blob/ade562c8cf5bcbeda2a1caca8cbfbe1538109aca/lib/http.js#L188-L199

which calls on:
https://github.com/digitalbazaar/bedrock-vc-issuer/blob/ade562c8cf5bcbeda2a1caca8cbfbe1538109aca/lib/rlc.js#L87-L110

**Comment by dlongley** [comment]
No longer relevant, closing.
