### ISSUE TITLE
Ensure account creation and data model is up to date with latest bedrock-profile-* code

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-vc-issuer#56]
This code includes a `capabilityAgentSeed` and assigns a `controller` to the account. Is this up to date with the latest thinking/code with bedrock-profile*?

https://github.com/digitalbazaar/bedrock-vc-issuer/blob/ade562c8cf5bcbeda2a1caca8cbfbe1538109aca/lib/http.js#L47-L58

@gannan08 -- could you take a look at this and confirm we need changes here? My inkling is that accounts can have N profile agents and that there is no "capabilityAgentSeed" in an `account` anymore, but this sort of thing is handled by the profile code instead. If so, step one here may be just removing `capabilityAgentSeed` (ideally this has no effect and is just an artifact of an old design). Step two would be addressing the issue with `controller` here -- probably removing it and instead using the profile APIs to look up a matching profile agent (profileAgent === holder ID from the VP) to get the account it is associated with.

**Comment by gannan08** [comment]
> This code includes a `capabilityAgentSeed` and assigns a `controller` to the account. Is this up to date with the latest thinking/code with bedrock-profile*?

No. This is out of date.

> @gannan08 -- could you take a look at this and confirm we need changes here? My inkling is that accounts can have N profile agents and that there is no "capabilityAgentSeed" in an `account` anymore, but this sort of thing is handled by the profile code instead.

Correct.

> If so, step one here may be just removing `capabilityAgentSeed` (ideally this has no effect and is just an artifact of an old design).

Agreed. We should remove `capabilityAgentSeed`. It was the precursor to bedrock-profile*.

> Step two would be addressing the issue with `controller` here -- probably removing it and instead using the profile APIs to look up a matching profile agent (profileAgent === holder ID from the VP) to get the account it is associated with.

Upon successful verification of the VP, we can extract the holder ID and match it with the profileAgent. That's fine.

Next, we use the profileAgent to find its associated account. Are you suggesting that we use the account to create an authenticated session? We have multiple profile agents that can be bound to the same account. Is it okay that we are creating different sessions for the **same account** for **different profile agents**?

@dlongley

**Comment by dlongley** [comment]
> Next, we use the profileAgent to find its associated account. Are you suggesting that we use the account to create an authenticated session? We have multiple profile agents that can be bound to the same account. Is it okay that we are creating different sessions for the same account for different profile agents?

I'm trying to parse your question. There's only one session that's ever in play at once here -- we're talking about a single session in a single browser -- and that session is associated with a single account. Are you asking: Is it ok that you can establish that session by authenticating as any of your profile agents? If so, I think the answer is "yes, for this application" (the application is VC issuer software). I don't think it matters which profile agent you use. Do you think otherwise, if so, why?

**Comment by dlongley** [comment]
Closing as removed. New service model does not involve accounts on services.
