### ISSUE TITLE
Make Collection.js it's own library?

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-vc-issuer#61]
Noticed that https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js is being used in other places as well like here https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/Collection.js. Not sure if we will need this in more libraries in future, if we do we might want to consider making it a standalone library.

**Comment by dlongley** [comment]
Closing as no longer needed / or some variant of it was implemented via bedrock-service-agent.
