### ISSUE TITLE
VC HTTP Api options are not supported

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-vc-issuer#75]
https://github.com/digitalbazaar/bedrock-vc-issuer/blob/28098492c9f92245967f5b75ee0d0de9c332a798/lib/http.js#L43-L63

The issuer needs to support the latest VC HTTP API options: https://w3c-ccg.github.io/vc-api/#issue-credential

**Comment by dlongley** [comment]
There are pending PRs to remove the options mentioned -- so we don't plan on implementing them. Closing.
