### ISSUE TITLE
Add `refreshService` using middleware to issuer endpoint

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-vc-issuer#90]
We have a growing number of options to add to a Vc before issuing. In order to avoid growing the `bedrock-vc-issuer` library with code for features that might not be used in every situation I propose adding `refreshService` as a piece of [express middleware](https://expressjs.com/en/guide/using-middleware.html) that checks if the issuer being called on has a setting for `refreshService` and amends the Vc to be issued with `refreshService` before it even hits the `issuer/:id` route. Where to store the code for refreshService becomes another issue entirely, but this reduces the amount of code needed inside of this library for adding `refreshService` to a Vc.

Example:
```js
import {addRefreshService} from 'bedrock-vc-refresh-service';
 app.post(
    routes.credentialsIssue,
    cors(),
    validate({bodySchema: issueCredentialBody}),
    getConfigMiddleware,
    // FIXME: add middleware to switch between oauth2 / zcap based on headers
    middleware.authorizeConfigZcapInvocation(),
   addRefreshService()
```

In turn `addRefreshService` would use the existing config middleware from `@bedrock/service-core`

Additionally if we separate core logic and http logic as proposed here: https://github.com/digitalbazaar/bedrock-vc-issuer/issues/91 then the refresh logic would exist entirely outside of this library and would only need to be required in the `issuer-http` lib.

**Comment by dlongley** [comment]
I'm having trouble following this, just like I did with #91. I think we should have a voice meeting about this subject in the near future with the necessary parties.

**Comment by dlongley** [comment]
We should close this issue, it sounds like there was a misunderstanding of the architecture / responsibilities.
