### ISSUE TITLE
Separate `bedrock-vc-issuer` and `bedrock-vc-issuer-http`

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-vc-issuer#91]
Unlike most bedrock libraries this service has both the `http` and buisness logic in one library.
This creates problems when the `issuing` business logic might be needed elsewhere (such as refreshing Vcs).
We should create ` bedrock-vc-issuer-http` which requires this library and uses the issuer from `bedrock-vc-issuer`

**Comment by dlongley** [comment]
I'd like to understand this more -- as it sounds at first glance to be a layering / abstraction violation. There may be a misunderstanding on how the components in the VC API fit together and what their responsibilities are -- or somewhere my part. So let's not implement anything related to this until we get more clarity.

**Comment by aljones15** [comment]
closing this as we have decided to not separate issuer from http at this time.
