### ISSUE TITLE
Update github actions to run with latest 18

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-vc-issuer#99]
https://github.com/digitalbazaar/bedrock-vc-issuer/pull/98

**Comment by dlongley** [comment]
We are waiting for https://github.com/nodejs/undici/pull/1628 (which was merged already) to land in the next version of node. That has the fix we need to re-enable node 18 support.

**Comment by dlongley** [comment]
This has been fixed and updated now. Thanks, @GertSallaerts!
